name: Release Extension

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          yarn set version classic
          yarn install --immutable

      - name: Build extension
        run: yarn build

      - name: Compress dist folder
        run: zip -r extension.zip dist

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          prerelease: false
          title: "Release ${{ github.ref }}"
          files: |
            *.zip
